---
title: 'PRAC2'
author: "Autor: Luis Leandro Jiménez y Edna Espejos"
date: "Diciembre 2020"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: 75.584-PEC-header.html
  word_document: default
  pdf_document:
    highlight: zenburn
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparación de los datos


## Estructura y composición general de los datos

1. Cargamos los datos

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Cargamos los paquetes R que vamos a usar
library(ggplot2)
library(dplyr)

totalData <- read.csv('winequality-red.csv',stringsAsFactors = FALSE)
filas=dim(totalData)[1]


```


2. Resumen de los datos 

```{r echo=TRUE, message=FALSE, warning=FALSE}

summary(totalData)
```

Se puede observar que todas las variables presentes en el dataset son númericos.


3.Estructura general de los datos

```{r echo=TRUE, message=FALSE, warning=FALSE}

str(totalData)
```


Seguimos observando el tipo de datos presente en nuestro conjunto de datos.


4. Valores nulos o perdidos

5. Outliers




